=== NEONScience/NEON-IS-data-processing/pack/NEONprocIS.base/inst/extdata/locations-sensor-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "required": [
    "type",
    "features",
    "source_type",
    "source_id"
  ],
  "properties": {
    "type": {
      "examples": [
        "FeatureCollection"
      ]
    },
    "features": {
      "type": ["array", "null"],
      "items": {
        "type": "object",
        "required": [
          "type",
          "geometry",
          "properties"
        ],
        "properties": {
          "type": {
            "type": "string",
            "examples": [
              "Feature"
            ]
          },
          "geometry": {
            "minLength": 1,
            "type": ["object", "null"],
            "examples": [
              "Point"
            ]
          },
          "properties": {
            "required": [
              "name",
              "site",
              "install_date",
              "remove_date",
              "context",
              "locations"
            ],
            "properties": {
              "name": {
                "type": "string",
                "examples": [
                  "CFGLOC108440"
                ]
              },
              "site": {
                "type": "string",
                "examples": [
                  "HARV"
                ]
              },
              "install_date": {
                "type": "string",
                "format": "date-time",
                "examples": [
                  "2017-02-07T00:17:20Z"
                ]
              },
              "remove_date": {
                "type": ["string", "null"],
                "format": "date-time",
                "examples": [
                  "2017-02-07T00:18:28Z"
                ]
              },
              "context": {
                "type": "array",
                "items": {
                  "minLength": 1,
                  "type": "string",
                  "examples": [
                    "soil"
                  ]
                }
              },
              "locations": {
                "type": "object",
                "minLength": 1,
                "required": [
                  "type",
                  "features"
                ],
                "properties": {
                  "type": {
                    "minLength": 1,
                    "type": "string",
                    "examples": [
                      "FeatureCollection"
                    ]
                  },
                  "features": {
                    "minLength": 1,
                    "type": "array",
                    "items": {
                      "minLength": 1,
                      "type": "object",
                      "required": [
                        "type",
                        "geometry",
                        "properties"
                      ],
                      "properties": {
                        "type": {
                          "minLength": 1,
                          "type": "string",
                          "examples": [
                            "Feature"
                          ]
                        },
                        "geometry": {
                          "minLength": 1,
                          "type": ["object", "null"],
                          "examples": [
                            "Point"
                          ]
                        },
                        "properties": {
                          "minLength": 1,
                          "type": "object",
                          "required": [
                            "start_date",
                            "end_date",
                            "z_offset",
                            "reference_location"
                          ],
                          "properties": {
                            "start_date": {
                              "minLength": 1,
                              "type": "string",
                              "format": "date-time",
                              "examples": [
                                "2010-01-01T00:00:00Z"
                              ]
                            },
                            "end_date": {
                              "minLength": 1,
                              "type": ["string", "null"],
                              "format": "date-time",
                              "examples": [
                                "2010-01-01T00:00:00Z"
                              ]
                            },
                            "z_offset": {
                              "minLength": 1,
                              "type": "number",
                              "examples": [
                                -0.02
                              ]
                            },
                            "reference_location": {
                              "minLength": 1,
                              "type": ["object","null"],
                              "properties": {
                                "type": {
                                  "minLength": 1,
                                  "type": "string",
                                  "examples": [
                                    "Feature"
                                  ]
                                },
                                "geometry": {
                                  "minLength": 1,
                                  "type": ["object", "null"],
                                  "examples": [
                                    "Point"
                                  ]
                                },
                                "properties": {
                                  "minLength": 1,
                                  "type": "object",
                                  "required": [
                                    "name",
                                    "locations"
                                  ],
                                  "properties": {
                                    "name": {
                                      "minLength": 1,
                                      "type": "string",
                                      "examples": [
                                        "SOILPL100441"
                                      ]
                                    },
                                    "locations": {
                                      "minLength": 1,
                                      "type": ["object", "null"],
                                      "required": [
                                        "type",
                                        "features"
                                      ],
                                      "properties": {
                                        "type": {
                                          "minLength": 1,
                                          "type": "string",
                                          "examples": [
                                            "FeatureCollection"
                                          ]
                                        },
                                        "features": {
                                          "minLength": 1,
                                          "type": "array",
                                          "items": {
                                            "minLength": 1,
                                            "type": "object",
                                            "required": [
                                              "type",
                                              "geometry",
                                              "properties"
                                            ],
                                            "properties": {
                                              "type": {
                                                "minLength": 1,
                                                "type": "string",
                                                "examples": [
                                                  "Feature"
                                                ]
                                              },
                                              "geometry": {
                                                "minLength": 1,
                                                "type": ["object", "null"],
                                                "examples": [
                                                  "Point"
                                                ]
                                              },
                                              "properties": {
                                                "minLength": 1,
                                                "type": "object",
                                                "required": [
                                                  "start_date",
                                                  "end_date",
                                                  "z_offset",
                                                  "reference_location"
                                                ],
                                                "properties": {
                                                  "start_date": {
                                                    "type": "string",
                                                    "format": "date-time",
                                                    "examples": [
                                                      "2010-01-01T00:00:00Z"
                                                    ]
                                                  },
                                                  "end_date": {
                                                    "type": ["string", "null"],
                                                    "format": "date-time",
                                                    "examples": [
                                                      "2010-01-01T00:00:00Z"
                                                    ]
                                                  },
                                                  "z_offset": {
                                                    "minLength": 1,
                                                    "type": "number",
                                                    "examples": [
                                                      0.00
                                                    ]
                                                  },
                                                  "reference_location": {
                                                    "minLength": 1,
                                                    "type": ["object","null"],
                                                    "properties": {
                                                      "type": {
                                                        "minLength": 1,
                                                        "type": "string",
                                                        "examples": [
                                                          "Feature"
                                                        ]
                                                      },
                                                      "geometry": {
                                                        "minLength": 1,
                                                        "type": ["string", "null"],
                                                        "examples": [
                                                          "Point"
                                                        ]
                                                      },
                                                      "properties": {
                                                        "minLength": 1,
                                                        "type": "object",
                                                        "required": [
                                                          "name",
                                                          "locations"
                                                        ],
                                                        "properties": {
                                                          "name": {
                                                            "minLength": 1,
                                                            "type": "string",
                                                            "examples": [
                                                              "SOILPL100441"
                                                            ]
                                                          },
                                                          "locations": {
                                                            "minLength": 1,
                                                            "examples": [
                                                              null
                                                            ]
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "Required Asset Management Location ID": {
            "minLength": 1,
            "type": "integer",
            "examples": [
              9915
            ]
          },
          "Required Asset Management Location Code": {
            "minLength": 1,
            "type": "string",
            "examples": [
              "CFGLOC108440"
            ]
          }
        }
      }
    },
    "source_type": {
      "type": "string",
      "examples": [
        "prt"
      ]
    },
    "source_id": {
      "type": "integer",
      "examples": [
        19963
      ]
    }
  }
}

=== NEONScience/NEON-IS-data-processing/pack/NEONprocIS.base/tests/testthat/testdataJson/locations-0lvl-ref-locs.json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": null,
      "properties": {
        "name": "CFGLOC101663",
        "site": "POSE",
        "install_date": "2019-09-04T15:10:48Z",
        "remove_date": null,
        "context": [
          "surfacewater",
          "water-quality"
        ],
        "group": [
            "water-quality-237"
        ],
        "locations": {
          "type": "FeatureCollection",
          "features": [
            {
              "type": "Feature",
              "geometry": {
                "type": "Point",
                "coordinates": [
                  -78.147286,
                  38.894397,
                  275.79
                ]
              },
              "properties": {
                "start_date": "2010-01-01T00:00:00Z",
                "end_date": null,
                "transaction_date": "2016-02-17T18:05:39Z",
                "alpha": 0,
                "beta": 0,
                "gamma": 0,
                "x_offset": 0.06731,
                "y_offset": 0.12,
                "z_offset": 0.06,
                "location_properties":[
                                    [
                                        "Country",
                                        "USA"
                                    ],
                                    [
                                        "UTM Zone",
                                        "13N"
                                    ],
                                    [
                                        "Geodetic datum",
                                        "WGS84"
                                    ],
                                    [
                                        "State province",
                                        "CO"
                                    ]
                ],
                "reference_location": {
                    "geometry": null,
                    "properties": {
                        "locations": {
                            "features": [
                                {
                                    "geometry": {
                                        "coordinates": [
                                            -103.02929,
                                            40.461927,
                                            1364.63056
                                        ],
                                        "type": "Point"
                                    },
                                    "properties": {
                                        "alpha": 0.0,
                                        "beta": 0.0,
                                        "end_date": null,
                                        "gamma": 0.0,
                                        "location_properties": [
                                            [
                                                "Country",
                                                "USA"
                                            ],
                                            [
                                                "County",
                                                "Logan"
                                            ],
                                            [
                                                "Geodetic datum",
                                                "WGS84"
                                            ],
                                            [
                                                "State province",
                                                "CO"
                                            ],
                                            [
                                                "x Azimuth Angle",
                                                270.0
                                            ],
                                            [
                                                "UTM Zone",
                                                "13N"
                                            ],
                                            [
                                                "y Azimuth Angle",
                                                180.0
                                            ],
                                            [
                                                "DistZaxsLvlMeasTow",
                                                "0.56,1.85,4.94,8.30"
                                            ],
                                            [
                                                "TimeTube",
                                                "11.54,12.09,12.27,12.44"
                                            ],
                                            [
                                                "DistZaxsTow",
                                                "7.93"
                                            ]
                                        ],
                                        "reference_location": null,
                                        "start_date": "2010-01-01T00:00:00Z",
                                        "x_offset": 0.0,
                                        "y_offset": 0.0,
                                        "z_offset": 0.0
                                    },
                                    "type": "Feature"
                                }
                            ],
                            "type": "FeatureCollection"
                        },
                        "name": "TOWER100002"
                    },
                    "type": "Feature"
                }
              }
            }
          ]
        },
        "site_location": {
          "features": [
              {
                  "geometry": {
                      "coordinates": [
                          -103.02929,
                          40.461894,
                          1364.63056
                      ],
                      "type": "Point"
                  },
                  "properties": {
                      "alpha": 0.0,
                      "beta": 0.0,
                      "end_date": null,
                      "gamma": 0.0,
                      "location_properties": [
                          [
                              "UTM Zone",
                              "13N"
                          ],
                          [
                              "Country",
                              "USA"
                          ],
                          [
                              "County",
                              "Logan"
                          ],
                          [
                              "Geodetic datum",
                              "WGS84"
                          ],
                          [
                              "State province",
                              "CO"
                          ]
                      ],
                      "reference_location": null,
                      "start_date": "2010-01-01T00:00:00Z",
                      "x_offset": 0.0,
                      "y_offset": 0.0,
                      "z_offset": 0.0
                  },
                  "type": "Feature"
              }
          ],
          "type": "FeatureCollection"
      }
      },
      "Required Asset Management Location ID": 2988,
      "Required Asset Management Location Code": "CFGLOC101663",
      "HOR": "101",
      "VER": "100",
      "TMI": "000",
      "Data Rate": "1"
    }
  ],
  "source_type": "prt",
  "source_id": 16247
}

=== NEONScience/NEON-IS-data-processing/pack/NEONprocIS.base/tests/testthat/locations-0lvl-ref-locs.json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": null,
      "properties": {
        "name": "CFGLOC101663",
        "site": "POSE",
        "install_date": "2019-09-04T15:10:48Z",
        "remove_date": null,
        "transaction_date": "2019-09-04T15:10:53Z",
        "context": [
          "surfacewater",
          "water-quality-237",
          "water-quality"
        ],
        "locations": {
          "type": "FeatureCollection",
          "features": [
            {
              "type": "Feature",
              "geometry": {
                "type": "Point",
                "coordinates": [
                  -78.147286,
                  38.894397,
                  275.79
                ]
              },
              "properties": {
                "start_date": "2010-01-01T00:00:00Z",
                "end_date": null,
                "transaction_date": "2016-02-17T18:05:39Z",
                "alpha": 0,
                "beta": 0,
                "gamma": 0,
                "x_offset": 0.06731,
                "y_offset": 0.12,
                "z_offset": 0.06,
                "reference_location": {
                  "type": "Feature",
                  "geometry": null,
                  "properties": {
                    "name": "S1LOC101258",
                    "locations": null
                  }
                }
              }
            }
          ]
        }
      },
      "Required Asset Management Location ID": 2988,
      "Required Asset Management Location Code": "CFGLOC101663",
      "HOR": "101",
      "VER": "100",
      "TMI": "000",
      "Data Rate": "1"
    }
  ],
  "source_type": "prt",
  "source_id": 16247
}
