=== NEONScience/NEON-IS-data-processing/pack/NEONprocIS.base/inst/extdata/locations-sensor-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "required": [
    "type",
    "features",
    "source_type",
    "source_id"
  ],
  "properties": {
    "type": {
      "examples": [
        "FeatureCollection"
      ]
    },
    "features": {
      "type": ["array", "null"],
      "items": {
        "type": "object",
        "required": [
          "type",
          "geometry",
          "properties"
        ],
        "properties": {
          "type": {
            "type": "string",
            "examples": [
              "Feature"
            ]
          },
          "geometry": {
            "minLength": 1,
            "type": ["object", "null"],
            "examples": [
              "Point"
            ]
          },
          "properties": {
            "required": [
              "name",
              "site",
              "install_date",
              "remove_date",
              "context",
              "locations"
            ],
            "properties": {
              "name": {
                "type": "string",
                "examples": [
                  "CFGLOC108440"
                ]
              },
              "site": {
                "type": "string",
                "examples": [
                  "HARV"
                ]
              },
              "install_date": {
                "type": "string",
                "format": "date-time",
                "examples": [
                  "2017-02-07T00:17:20Z"
                ]
              },
              "remove_date": {
                "type": ["string", "null"],
                "format": "date-time",
                "examples": [
                  "2017-02-07T00:18:28Z"
                ]
              },
              "context": {
                "type": "array",
                "items": {
                  "minLength": 1,
                  "type": "string",
                  "examples": [
                    "soil"
                  ]
                }
              },
              "locations": {
                "type": "object",
                "minLength": 1,
                "required": [
                  "type",
                  "features"
                ],
                "properties": {
                  "type": {
                    "minLength": 1,
                    "type": "string",
                    "examples": [
                      "FeatureCollection"
                    ]
                  },
                  "features": {
                    "minLength": 1,
                    "type": "array",
                    "items": {
                      "minLength": 1,
                      "type": "object",
                      "required": [
                        "type",
                        "geometry",
                        "properties"
                      ],
                      "properties": {
                        "type": {
                          "minLength": 1,
                          "type": "string",
                          "examples": [
                            "Feature"
                          ]
                        },
                        "geometry": {
                          "minLength": 1,
                          "type": ["object", "null"],
                          "examples": [
                            "Point"
                          ]
                        },
                        "properties": {
                          "minLength": 1,
                          "type": "object",
                          "required": [
                            "start_date",
                            "end_date",
                            "z_offset",
                            "reference_location"
                          ],
                          "properties": {
                            "start_date": {
                              "minLength": 1,
                              "type": "string",
                              "format": "date-time",
                              "examples": [
                                "2010-01-01T00:00:00Z"
                              ]
                            },
                            "end_date": {
                              "minLength": 1,
                              "type": ["string", "null"],
                              "format": "date-time",
                              "examples": [
                                "2010-01-01T00:00:00Z"
                              ]
                            },
                            "z_offset": {
                              "minLength": 1,
                              "type": "number",
                              "examples": [
                                -0.02
                              ]
                            },
                            "reference_location": {
                              "minLength": 1,
                              "type": ["object","null"],
                              "properties": {
                                "type": {
                                  "minLength": 1,
                                  "type": "string",
                                  "examples": [
                                    "Feature"
                                  ]
                                },
                                "geometry": {
                                  "minLength": 1,
                                  "type": ["object", "null"],
                                  "examples": [
                                    "Point"
                                  ]
                                },
                                "properties": {
                                  "minLength": 1,
                                  "type": "object",
                                  "required": [
                                    "name",
                                    "locations"
                                  ],
                                  "properties": {
                                    "name": {
                                      "minLength": 1,
                                      "type": "string",
                                      "examples": [
                                        "SOILPL100441"
                                      ]
                                    },
                                    "locations": {
                                      "minLength": 1,
                                      "type": ["object", "null"],
                                      "required": [
                                        "type",
                                        "features"
                                      ],
                                      "properties": {
                                        "type": {
                                          "minLength": 1,
                                          "type": "string",
                                          "examples": [
                                            "FeatureCollection"
                                          ]
                                        },
                                        "features": {
                                          "minLength": 1,
                                          "type": "array",
                                          "items": {
                                            "minLength": 1,
                                            "type": "object",
                                            "required": [
                                              "type",
                                              "geometry",
                                              "properties"
                                            ],
                                            "properties": {
                                              "type": {
                                                "minLength": 1,
                                                "type": "string",
                                                "examples": [
                                                  "Feature"
                                                ]
                                              },
                                              "geometry": {
                                                "minLength": 1,
                                                "type": ["object", "null"],
                                                "examples": [
                                                  "Point"
                                                ]
                                              },
                                              "properties": {
                                                "minLength": 1,
                                                "type": "object",
                                                "required": [
                                                  "start_date",
                                                  "end_date",
                                                  "z_offset",
                                                  "reference_location"
                                                ],
                                                "properties": {
                                                  "start_date": {
                                                    "type": "string",
                                                    "format": "date-time",
                                                    "examples": [
                                                      "2010-01-01T00:00:00Z"
                                                    ]
                                                  },
                                                  "end_date": {
                                                    "type": ["string", "null"],
                                                    "format": "date-time",
                                                    "examples": [
                                                      "2010-01-01T00:00:00Z"
                                                    ]
                                                  },
                                                  "z_offset": {
                                                    "minLength": 1,
                                                    "type": "number",
                                                    "examples": [
                                                      0.00
                                                    ]
                                                  },
                                                  "reference_location": {
                                                    "minLength": 1,
                                                    "type": ["object","null"],
                                                    "properties": {
                                                      "type": {
                                                        "minLength": 1,
                                                        "type": "string",
                                                        "examples": [
                                                          "Feature"
                                                        ]
                                                      },
                                                      "geometry": {
                                                        "minLength": 1,
                                                        "type": ["string", "null"],
                                                        "examples": [
                                                          "Point"
                                                        ]
                                                      },
                                                      "properties": {
                                                        "minLength": 1,
                                                        "type": "object",
                                                        "required": [
                                                          "name",
                                                          "locations"
                                                        ],
                                                        "properties": {
                                                          "name": {
                                                            "minLength": 1,
                                                            "type": "string",
                                                            "examples": [
                                                              "SOILPL100441"
                                                            ]
                                                          },
                                                          "locations": {
                                                            "minLength": 1,
                                                            "examples": [
                                                              null
                                                            ]
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "Required Asset Management Location ID": {
            "minLength": 1,
            "type": "integer",
            "examples": [
              9915
            ]
          },
          "Required Asset Management Location Code": {
            "minLength": 1,
            "type": "string",
            "examples": [
              "CFGLOC108440"
            ]
          }
        }
      }
    },
    "source_type": {
      "type": "string",
      "examples": [
        "prt"
      ]
    },
    "source_id": {
      "type": "integer",
      "examples": [
        19963
      ]
    }
  }
}

=== NEONScience/NEON-IS-data-processing/flow/tests/testthat/pfs/regularization/ptb330a/2020/01/01/CFGLOC100959/location/ptb330a_43734_locations.json
{
    "type":"FeatureCollection",
    "features":[
        {
            "type":"Feature",
            "geometry":null,
            "properties":{
                "name":"CFGLOC100959",
                "domain":"D01",
                "site":"HARV",
                "install_date":"2020-01-01T00:00:00Z",
                "remove_date":"2020-01-02T00:00:00Z",
                "context":[

                ],
                "locations":{
                    "type":"FeatureCollection",
                    "features":[
                        {
                            "type":"Feature",
                            "geometry":null,
                            "properties":{
                                "start_date":"2020-01-01T00:00:00Z",
                                "end_date":"2020-01-02T00:00:00Z",
                                "alpha":                                0,
                                "beta":                                0,
                                "gamma":                                0,
                                "x_offset":                                -0.03,
                                "y_offset":                                1.71,
                                "z_offset":                                5.65,
                                "reference_location":{
                                    "type":"Feature",
                                    "geometry":null,
                                    "properties":{
                                        "name":"TOWER100450",
                                        "locations":{
                                            "type":"FeatureCollection",
                                            "features":[
                                                {
                                                    "type":"Feature",
                                                    "geometry":{
                                                        "type":"Point",
                                                        "coordinates":[
                                                                                                                        -72.17265,
                                                                                                                        42.53691,
                                                                                                                        348.12784
                                                        ]
                                                    },
                                                    "properties":{
                                                        "start_date":"2020-01-01T00:00:00Z",
                                                        "end_date":"2020-01-02T00:00:00Z",
                                                        "alpha":                                                        0,
                                                        "beta":                                                        0,
                                                        "gamma":                                                        0,
                                                        "x_offset":                                                        0,
                                                        "y_offset":                                                        0,
                                                        "z_offset":                                                        0,
                                                        "reference_location":null,
                                                        "location_properties":[
                                                            [
                                                                "UTM Zone",
                                                                "18N"
                                                            ],
                                                            [
                                                                "State province",
                                                                "MA"
                                                            ],
                                                            [
                                                                "Country",
                                                                "USA"
                                                            ],
                                                            [
                                                                "County",
                                                                "Worcester"
                                                            ],
                                                            [
                                                                "Geodetic datum",
                                                                "WGS84"
                                                            ],
                                                            [
                                                                "y Azimuth Angle",
                                                                                                                                180
                                                            ],
                                                            [
                                                                "x Azimuth Angle",
                                                                                                                                270
                                                            ]
                                                        ]
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                },
                                "location_properties":[
                                    [
                                        "UTM Zone",
                                        "18N"
                                    ],
                                    [
                                        "County",
                                        "Worcester"
                                    ],
                                    [
                                        "Country",
                                        "USA"
                                    ],
                                    [
                                        "Geodetic datum",
                                        "WGS84"
                                    ],
                                    [
                                        "State province",
                                        "MA"
                                    ],
                                    [
                                        "Elevation uncertainty",
                                                                                0.02
                                    ]
                                ]
                            }
                        }
                    ]
                }
            },
            "HOR":"000",
            "Required Asset Management Location Code":"CFGLOC100959",
            "TMI":"000",
            "Data Rate":"0.1",
            "VER":"025",
            "Required Asset Management Location ID":            2000,
            "FreqSamp":"0.1",
            "Cal$PrdLab":"1",
            "IdxLoca":"000_025"
        }
    ],
    "source_id":    43734,
    "source_type":"ptb330a"
}

=== NEONScience/NEON-IS-data-processing/pack/NEONprocIS.base/tests/testthat/testdataJson/locations-wStartDate-wEndDate.json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": null,
      "properties": {
        "name": "CFGLOC108440",
        "site": "HARV",
        "install_date": "2017-02-07T00:17:20Z",
        "remove_date": "2017-02-07T00:18:28Z",
        "context": [
          "soil"
        ],
        "locations": {
          "type": "FeatureCollection",
          "features": [
            {
              "type": "Feature",
              "geometry": null,
              "properties": {
                "start_date": "2010-01-01T00:00:00Z",
                "end_date": "2010-01-02T00:00:00Z",
                "z_offset": -0.02,
                "reference_location": {
                  "type": "Feature",
                  "geometry": null,
                  "properties": {
                    "name": "SOILPL100441",
                    "locations": {
                      "type": "FeatureCollection",
                      "features": [
                        {
                          "type": "Feature",
                          "geometry": null,
                          "properties": {
                            "start_date": "2010-01-01T00:00:00Z",
                            "end_date": "2010-01-02T00:00:00Z",
                            "z_offset": 0,
                            "reference_location": {
                              "type": "Feature",
                              "geometry": null,
                              "properties": {
                                "name": "SOILPL100441",
                                "locations": null
                              }
                            }
                          }
                        }
                      ]
                    }
                  }
                }
              }
            }
          ]
        }
      },
      "Required Asset Management Location ID": 9915,
      "Required Asset Management Location Code": "CFGLOC108440"
    }
  ],
  "source_type": "prt",
  "source_id": 19963
}
