=== NEONScience/NEON-IS-data-processing/pack/NEONprocIS.base/inst/extdata/locations-sensor-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "required": [
    "type",
    "features",
    "source_type",
    "source_id"
  ],
  "properties": {
    "type": {
      "examples": [
        "FeatureCollection"
      ]
    },
    "features": {
      "type": ["array", "null"],
      "items": {
        "type": "object",
        "required": [
          "type",
          "geometry",
          "properties"
        ],
        "properties": {
          "type": {
            "type": "string",
            "examples": [
              "Feature"
            ]
          },
          "geometry": {
            "minLength": 1,
            "type": ["object", "null"],
            "examples": [
              "Point"
            ]
          },
          "properties": {
            "required": [
              "name",
              "site",
              "install_date",
              "remove_date",
              "context",
              "locations"
            ],
            "properties": {
              "name": {
                "type": "string",
                "examples": [
                  "CFGLOC108440"
                ]
              },
              "site": {
                "type": "string",
                "examples": [
                  "HARV"
                ]
              },
              "install_date": {
                "type": "string",
                "format": "date-time",
                "examples": [
                  "2017-02-07T00:17:20Z"
                ]
              },
              "remove_date": {
                "type": ["string", "null"],
                "format": "date-time",
                "examples": [
                  "2017-02-07T00:18:28Z"
                ]
              },
              "context": {
                "type": "array",
                "items": {
                  "minLength": 1,
                  "type": "string",
                  "examples": [
                    "soil"
                  ]
                }
              },
              "locations": {
                "type": "object",
                "minLength": 1,
                "required": [
                  "type",
                  "features"
                ],
                "properties": {
                  "type": {
                    "minLength": 1,
                    "type": "string",
                    "examples": [
                      "FeatureCollection"
                    ]
                  },
                  "features": {
                    "minLength": 1,
                    "type": "array",
                    "items": {
                      "minLength": 1,
                      "type": "object",
                      "required": [
                        "type",
                        "geometry",
                        "properties"
                      ],
                      "properties": {
                        "type": {
                          "minLength": 1,
                          "type": "string",
                          "examples": [
                            "Feature"
                          ]
                        },
                        "geometry": {
                          "minLength": 1,
                          "type": ["object", "null"],
                          "examples": [
                            "Point"
                          ]
                        },
                        "properties": {
                          "minLength": 1,
                          "type": "object",
                          "required": [
                            "start_date",
                            "end_date",
                            "z_offset",
                            "reference_location"
                          ],
                          "properties": {
                            "start_date": {
                              "minLength": 1,
                              "type": "string",
                              "format": "date-time",
                              "examples": [
                                "2010-01-01T00:00:00Z"
                              ]
                            },
                            "end_date": {
                              "minLength": 1,
                              "type": ["string", "null"],
                              "format": "date-time",
                              "examples": [
                                "2010-01-01T00:00:00Z"
                              ]
                            },
                            "z_offset": {
                              "minLength": 1,
                              "type": "number",
                              "examples": [
                                -0.02
                              ]
                            },
                            "reference_location": {
                              "minLength": 1,
                              "type": ["object","null"],
                              "properties": {
                                "type": {
                                  "minLength": 1,
                                  "type": "string",
                                  "examples": [
                                    "Feature"
                                  ]
                                },
                                "geometry": {
                                  "minLength": 1,
                                  "type": ["object", "null"],
                                  "examples": [
                                    "Point"
                                  ]
                                },
                                "properties": {
                                  "minLength": 1,
                                  "type": "object",
                                  "required": [
                                    "name",
                                    "locations"
                                  ],
                                  "properties": {
                                    "name": {
                                      "minLength": 1,
                                      "type": "string",
                                      "examples": [
                                        "SOILPL100441"
                                      ]
                                    },
                                    "locations": {
                                      "minLength": 1,
                                      "type": ["object", "null"],
                                      "required": [
                                        "type",
                                        "features"
                                      ],
                                      "properties": {
                                        "type": {
                                          "minLength": 1,
                                          "type": "string",
                                          "examples": [
                                            "FeatureCollection"
                                          ]
                                        },
                                        "features": {
                                          "minLength": 1,
                                          "type": "array",
                                          "items": {
                                            "minLength": 1,
                                            "type": "object",
                                            "required": [
                                              "type",
                                              "geometry",
                                              "properties"
                                            ],
                                            "properties": {
                                              "type": {
                                                "minLength": 1,
                                                "type": "string",
                                                "examples": [
                                                  "Feature"
                                                ]
                                              },
                                              "geometry": {
                                                "minLength": 1,
                                                "type": ["object", "null"],
                                                "examples": [
                                                  "Point"
                                                ]
                                              },
                                              "properties": {
                                                "minLength": 1,
                                                "type": "object",
                                                "required": [
                                                  "start_date",
                                                  "end_date",
                                                  "z_offset",
                                                  "reference_location"
                                                ],
                                                "properties": {
                                                  "start_date": {
                                                    "type": "string",
                                                    "format": "date-time",
                                                    "examples": [
                                                      "2010-01-01T00:00:00Z"
                                                    ]
                                                  },
                                                  "end_date": {
                                                    "type": ["string", "null"],
                                                    "format": "date-time",
                                                    "examples": [
                                                      "2010-01-01T00:00:00Z"
                                                    ]
                                                  },
                                                  "z_offset": {
                                                    "minLength": 1,
                                                    "type": "number",
                                                    "examples": [
                                                      0.00
                                                    ]
                                                  },
                                                  "reference_location": {
                                                    "minLength": 1,
                                                    "type": ["object","null"],
                                                    "properties": {
                                                      "type": {
                                                        "minLength": 1,
                                                        "type": "string",
                                                        "examples": [
                                                          "Feature"
                                                        ]
                                                      },
                                                      "geometry": {
                                                        "minLength": 1,
                                                        "type": ["string", "null"],
                                                        "examples": [
                                                          "Point"
                                                        ]
                                                      },
                                                      "properties": {
                                                        "minLength": 1,
                                                        "type": "object",
                                                        "required": [
                                                          "name",
                                                          "locations"
                                                        ],
                                                        "properties": {
                                                          "name": {
                                                            "minLength": 1,
                                                            "type": "string",
                                                            "examples": [
                                                              "SOILPL100441"
                                                            ]
                                                          },
                                                          "locations": {
                                                            "minLength": 1,
                                                            "examples": [
                                                              null
                                                            ]
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "Required Asset Management Location ID": {
            "minLength": 1,
            "type": "integer",
            "examples": [
              9915
            ]
          },
          "Required Asset Management Location Code": {
            "minLength": 1,
            "type": "string",
            "examples": [
              "CFGLOC108440"
            ]
          }
        }
      }
    },
    "source_type": {
      "type": "string",
      "examples": [
        "prt"
      ]
    },
    "source_id": {
      "type": "integer",
      "examples": [
        19963
      ]
    }
  }
}

=== NEONScience/NEON-IS-data-processing/flow/flow.loc.asgn/tests/testthat/pfs/locations/prt/24688/prt_24688_locations.json
{
    "type":"FeatureCollection",
    "features":[
        {
            "type":"Feature",
            "geometry":null,
            "properties":{
                "name":"CFGLOC101754",
                "site":"CPER",
                "install_date":"2019-01-04T00:00:00Z",
                "remove_date":"2019-01-06T00:00:00Z",
                "context":[
                    "soil"
                ],
                "locations":{
                    "type":"FeatureCollection",
                    "features":[
                        {
                            "type":"Feature",
                            "geometry":null,
                            "properties":{
                                "start_date":"2019-01-04T00:00:00Z",
                                "end_date":"2019-01-06T00:00:00Z",
                                "alpha":                                2,
                                "beta":                                0,
                                "gamma":                                45,
                                "x_offset":                                0.5,
                                "y_offset":                                2.8,
                                "z_offset":                                -1.96,
                                "reference_location":{
                                    "type":"Feature",
                                    "geometry":null,
                                    "properties":{
                                        "name":"SOILPL100212",
                                        "locations":{
                                            "type":"FeatureCollection",
                                            "features":[
                                                {
                                                    "type":"Feature",
                                                    "geometry":{
                                                        "type":"Polygon",
                                                        "coordinates":[
                                                            [
                                                                                                                                -104.74572,
                                                                                                                                40.81567,
                                                                                                                                1654.5211512
                                                            ],
                                                            [
                                                                                                                                -104.74568,
                                                                                                                                40.8157,
                                                                                                                                1654.1166816
                                                            ],
                                                            [
                                                                                                                                -104.74572,
                                                                                                                                40.81573,
                                                                                                                                1654.0980888
                                                            ],
                                                            [
                                                                                                                                -104.74576,
                                                                                                                                40.8157,
                                                                                                                                1654.4732976
                                                            ],
                                                            [
                                                                                                                                -104.74572,
                                                                                                                                40.81567,
                                                                                                                                1654.5211512
                                                            ]
                                                        ]
                                                    },
                                                    "properties":{
                                                        "start_date":"2019-01-05T00:00:00Z",
                                                        "end_date":"2019-01-06T00:00:00Z",
                                                        "alpha":                                                        0,
                                                        "beta":                                                        0,
                                                        "gamma":                                                        0,
                                                        "x_offset":                                                        0,
                                                        "y_offset":                                                        0,
                                                        "z_offset":                                                        0,
                                                        "reference_location":null,
                                                        "location_properties":[
                                                            [
                                                                "UTM Zone",
                                                                "13N"
                                                            ]
                                                        ]
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                },
                                "location_properties":[
                                    [
                                        "UTM Zone",
                                        "13N"
                                    ],
                                    [
                                        "Geodetic datum",
                                        "WGS84"
                                    ],
                                    [
                                        "Country",
                                        "USA"
                                    ],
                                    [
                                        "State province",
                                        "CO"
                                    ],
                                    [
                                        "County",
                                        "Weld"
                                    ]
                                ]
                            }
                        }
                    ]
                }
            },
            "Required Asset Management Location ID":            3103,
            "Required Asset Management Location Code":"CFGLOC101754",
            "HOR":"001",
            "VER":"509",
            "TMI":"000",
            "Data Rate":"0.1"
        }
    ],
    "source_id":    24688,
    "source_type":"prt"
}

=== NEONScience/NEON-IS-data-processing/flow/tests/testthat/pfs/surfacewaterPhysical_analyze_pad_and_qaqc_plau/2022/03/02/surfacewater-physical_ARIK101100/leveltroll500/CFGLOC101669/location/leveltroll500_43697_locations.json
{
    "features":[
        {
            "Data Rate":"0.0166666666667",
            "HOR":"101",
            "Required Asset Management Location Code":"CFGLOC101669",
            "Required Asset Management Location ID":            2994,
            "TMI":"000",
            "VER":"100",
            "geometry":null,
            "properties":{
                "context":[
                    "surfacewater"
                ],
                "domain":"D10",
                "install_date":"2022-03-02T00:00:00Z",
                "locations":{
                    "features":[
                        {
                            "geometry":{
                                "coordinates":[
                                                                        -102.450048,
                                                                        39.758552,
                                                                        1179.579
                                ],
                                "type":"Point"
                            },
                            "properties":{
                                "alpha":                                0,
                                "beta":                                0,
                                "end_date":"2022-03-03T00:00:00Z",
                                "gamma":                                0,
                                "location_properties":[
                                    [
                                        "Country",
                                        "USA"
                                    ],
                                    [
                                        "County",
                                        "Yuma"
                                    ],
                                    [
                                        "State province",
                                        "CO"
                                    ],
                                    [
                                        "Coordinate uncertainty",
                                                                                0.231
                                    ],
                                    [
                                        "Real world coordinate uncertainty",
                                                                                0.1
                                    ],
                                    [
                                        "Real world elevation uncertainty",
                                                                                0.1
                                    ],
                                    [
                                        "Survey vertical uncertainty",
                                                                                0.002
                                    ],
                                    [
                                        "Elevation uncertainty",
                                                                                0.1
                                    ],
                                    [
                                        "Survey horizontal uncertainty",
                                                                                0.018
                                    ],
                                    [
                                        "Transformation RMSE",
                                                                                0.131
                                    ],
                                    [
                                        "Coordinate source",
                                        "AIS_SURVEY"
                                    ],
                                    [
                                        "UTM Zone",
                                        "13N"
                                    ],
                                    [
                                        "Geodetic datum",
                                        "WGS84"
                                    ]
                                ],
                                "reference_location":null,
                                "start_date":"2022-03-02T00:00:00Z",
                                "x_offset":                                0.036,
                                "y_offset":                                0,
                                "z_offset":                                -0.343
                            },
                            "type":"Feature"
                        }
                    ],
                    "type":"FeatureCollection"
                },
                "name":"CFGLOC101669",
                "remove_date":"2022-03-03T00:00:00Z",
                "site":"ARIK"
            },
            "type":"Feature"
        }
    ],
    "source_id":    43697,
    "source_type":"leveltroll500",
    "type":"FeatureCollection"
}
